# Generated by Django 4.2.11 on 2024-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Order',
            new_name='order',
        ),
    ]
