# Generated by Django 4.2.11 on 2024-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_celeb_profile'),
        ('celeb_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebprofile',
            name='associated_products',
            field=models.ManyToManyField(blank=True, related_name='associated_celeb_profiles', to='products.product'),
        ),
    ]
