# Generated by Django 4.2.11 on 2024-03-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrequest',
            name='user',
        ),
    ]
