# Generated by Django 4.2.11 on 2024-03-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0003_remove_celebprofile_associated_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebprofile',
            old_name='added_products',
            new_name='products_added',
        ),
    ]
