# Generated by Django 4.2.11 on 2024-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0004_rename_added_products_celebprofile_products_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebprofile',
            name='display_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
