# Generated by Django 4.2.11 on 2024-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0006_alter_celebprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebprofile',
            name='small_bio',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='celebprofile',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
