# Generated by Django 4.2.11 on 2024-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0007_celebprofile_small_bio_alter_celebprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebprofile',
            name='bio',
            field=models.CharField(),
        ),
    ]
