# Generated by Django 4.2.11 on 2024-04-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0008_alter_celebprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebprofile',
            name='image_url',
        ),
    ]
