# Generated by Django 4.2.11 on 2024-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0009_remove_celebprofile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebprofile',
            name='image',
            field=models.ImageField(upload_to='celeb_images/'),
        ),
    ]
