# Generated by Django 4.2.11 on 2024-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0010_alter_celebprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
