# Generated by Django 4.2.11 on 2024-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0012_alter_celebprofile_small_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebprofile',
            name='social_media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
