# Generated by Django 4.2.11 on 2024-04-29 13:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb_profile', '0013_celebprofile_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
