# Generated by Django 4.2.11 on 2024-03-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_availability_shipping_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_in_stock',
        ),
    ]
