# Generated by Django 4.2.11 on 2024-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_display_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
