# Generated by Django 4.2.11 on 2024-04-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_small_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
