# Generated by Django 4.2.11 on 2024-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
